"""compatibility no-op after 007_add_saas_tenants.

This file was generated by an earlier handoff draft. The actual migration
content now lives in 007_add_saas_tenants.py. Keeping this revision as a no-op
prevents Alembic from seeing two independent heads while preserving the file
path referenced by older notes.
"""

from typing import Sequence, Union

revision: str = "007_add_tenants_and_multi_tenant_columns"
down_revision: Union[str, None] = "007_add_saas_tenants"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass

