"""add app_pass to site model

Revision ID: d8acec78d2d3
Revises: 008
Create Date: 2026-05-06 15:15:50.772446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8acec78d2d3'
down_revision: Union[str, None] = '008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_admin_audit_actor'), table_name='admin_audit_log')
    op.drop_index(op.f('idx_admin_audit_tenant_created'), table_name='admin_audit_log')
    op.create_index(op.f('ix_admin_audit_log_action'), 'admin_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_actor'), 'admin_audit_log', ['actor'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_tenant_id'), 'admin_audit_log', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_ai_provider_keys_status_health'), table_name='ai_provider_keys')
    op.drop_index(op.f('idx_ai_token_ledger_tenant'), table_name='ai_token_ledger')
    op.drop_index(op.f('ix_ai_ledger_ref'), table_name='ai_token_ledger')
    op.drop_constraint(op.f('ai_token_ledger_tenant_id_fkey'), 'ai_token_ledger', type_='foreignkey')
    op.drop_column('ai_token_ledger', 'tenant_id')
    op.drop_index(op.f('idx_ai_token_wallets_tenant'), table_name='ai_token_wallets')
    op.drop_constraint(op.f('ai_token_wallets_tenant_id_fkey'), 'ai_token_wallets', type_='foreignkey')
    op.drop_column('ai_token_wallets', 'tenant_id')
    op.drop_index(op.f('idx_ai_usage_tenant'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_license_created'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_plugin_created'), table_name='ai_usage')
    op.drop_constraint(op.f('ai_usage_tenant_id_fkey'), 'ai_usage', type_='foreignkey')
    op.drop_column('ai_usage', 'tenant_id')
    op.drop_index(op.f('ix_audit_log_resource'), table_name='audit_log')
    op.add_column('sites', sa.Column('app_pass', sa.String(length=255), nullable=True))
    op.drop_index(op.f('idx_tenants_domain'), table_name='tenants')
    op.drop_index(op.f('idx_tenants_license'), table_name='tenants')
    op.drop_constraint(op.f('uq_tenants_domain'), 'tenants', type_='unique')
    op.drop_constraint(op.f('uq_tenants_license_key'), 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_domain'), 'tenants', ['domain'], unique=True)
    op.create_index(op.f('ix_tenants_license_key'), 'tenants', ['license_key'], unique=True)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_index(op.f('ix_tenants_tier'), 'tenants', ['tier'], unique=False)
    op.drop_index(op.f('idx_token_transactions_tenant_created'), table_name='token_transactions')
    op.create_index(op.f('ix_token_transactions_tenant_id'), 'token_transactions', ['tenant_id'], unique=False)
    op.drop_index(op.f('idx_tokens_tenant'), table_name='tokens')
    op.create_index(op.f('ix_tokens_tenant_id'), 'tokens', ['tenant_id'], unique=False)
    op.drop_index(op.f('idx_usage_logs_tenant'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_license_created'), table_name='usage_logs')
    op.drop_constraint(op.f('usage_logs_tenant_id_fkey'), 'usage_logs', type_='foreignkey')
    op.drop_column('usage_logs', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_logs', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('usage_logs_tenant_id_fkey'), 'usage_logs', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_usage_logs_license_created'), 'usage_logs', ['license_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_usage_logs_tenant'), 'usage_logs', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_tokens_tenant_id'), table_name='tokens')
    op.create_index(op.f('idx_tokens_tenant'), 'tokens', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_token_transactions_tenant_id'), table_name='token_transactions')
    op.create_index(op.f('idx_token_transactions_tenant_created'), 'token_transactions', ['tenant_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_tenants_tier'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_license_key'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_domain'), table_name='tenants')
    op.create_unique_constraint(op.f('uq_tenants_license_key'), 'tenants', ['license_key'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_tenants_domain'), 'tenants', ['domain'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_tenants_license'), 'tenants', ['license_key'], unique=False)
    op.create_index(op.f('idx_tenants_domain'), 'tenants', ['domain'], unique=False)
    op.drop_column('sites', 'app_pass')
    op.create_index(op.f('ix_audit_log_resource'), 'audit_log', ['resource_type', 'resource_id'], unique=False)
    op.add_column('ai_usage', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('ai_usage_tenant_id_fkey'), 'ai_usage', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_ai_usage_plugin_created'), 'ai_usage', ['source_plugin', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_license_created'), 'ai_usage', ['license_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_ai_usage_tenant'), 'ai_usage', ['tenant_id'], unique=False)
    op.add_column('ai_token_wallets', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('ai_token_wallets_tenant_id_fkey'), 'ai_token_wallets', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('idx_ai_token_wallets_tenant'), 'ai_token_wallets', ['tenant_id'], unique=False)
    op.add_column('ai_token_ledger', sa.Column('tenant_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('ai_token_ledger_tenant_id_fkey'), 'ai_token_ledger', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_ai_ledger_ref'), 'ai_token_ledger', ['reference_type', 'reference_id'], unique=False)
    op.create_index(op.f('idx_ai_token_ledger_tenant'), 'ai_token_ledger', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ai_provider_keys_status_health'), 'ai_provider_keys', ['status', 'health_status'], unique=False)
    op.drop_index(op.f('ix_admin_audit_log_tenant_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_actor'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_action'), table_name='admin_audit_log')
    op.create_index(op.f('idx_admin_audit_tenant_created'), 'admin_audit_log', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_admin_audit_actor'), 'admin_audit_log', ['actor'], unique=False)
    # ### end Alembic commands ###
