"""add_customer_profile_fields

Revision ID: eabfff3ba783
Revises: d8acec78d2d3
Create Date: 2026-05-11 10:27:39.089341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eabfff3ba783'
down_revision: Union[str, None] = 'd8acec78d2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('application_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('site_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'site_url')
    op.drop_column('users', 'application_password')
    # ### end Alembic commands ###
